simple FTP translator
preludeorg/operator-support pull request #270
Opened 2021-07-12 22:19 UTC by lzimm

this is an example translator that allows us to proxy C2 traffic over FTP. the translator proxy serves as a dumb middle that does nothing more than redirect payloads directly to the HTTP Operator endpoint, where it expects `agent->operator` traffic to come over file uploads (`STOR` commands) and `operator->agent` traffic/responses to flow over file downloads (`RETR` commands).

provided are both a standalone `server.py` which serves as the ftp server / translator layer, as well as an example `agent.py` which is a light agent derived from schism but specialized to run command traffic over FTP, through the translator proxy.

2021-07-12 22:52 UTC, privateducky commented on tools/translators/ftp/server.py
> +    parser.add_argument('-A', '--address', required=False, default='http://localhost:3391')
can you add a -O option for Operator address, so the user can pass in an operator + an ftp location? Hard-coding port 21 is OK, as that's FTP.

2021-07-12 22:54 UTC, lzimm commented on tools/translators/ftp/server.py
> +    parser.add_argument('-A', '--address', required=False, default='http://localhost:3391')
you mean -O for Operator (instead of the -A its using now) then add an address for the actual FTP server to listen on?

2021-07-12 22:56 UTC, privateducky commented on tools/translators/ftp/server.py
> +            if file.endswith('target.txt'):
reading between the lines here... 'target.txt' is one end of the communication, in this case a beacon file to forward to Operator (not for consumption of the agent), right? 

if that's right (or backwards), can you create a private function on this class that describes it? Like:
```
def __beacon_for_operator(f_name):
    return f.name.endswith('target.txt')
```

2021-07-12 22:56 UTC, privateducky commented on tools/translators/ftp/server.py
> +    parser.add_argument('-A', '--address', required=False, default='http://localhost:3391')
ignore, this is the server

2021-07-12 22:57 UTC, privateducky commented on tools/translators/ftp/agent.py
> +        self.target = None
move target into the Beacon object itself

2021-07-12 22:59 UTC, privateducky commented on tools/translators/ftp/agent.py
> +            if len(res):
just ```if res``` to be Pythonic

2021-07-12 23:01 UTC, lzimm commented on tools/translators/ftp/agent.py
> +        self.target = None
ahh, i wasn't clear on how target is supposed to be used. if its just the FTP server IP we don't need that thing above with `target.txt`

2021-07-12 23:02 UTC, privateducky commented on tools/translators/ftp/agent.py
> +import base64
doesn't look like base64 is used.. let's use it, just to be consistent with Schism, as we may call this "Schism-FTP" or something

2021-07-12 23:02 UTC, privateducky requested changes
Couple of pretty minor things, after a code analysis. I'll actually run it in the a.m. 

Really solid work though.

2021-07-12 23:04 UTC, privateducky commented on tools/translators/ftp/agent.py
> +        self.target = None
so Target never got patched into Schism after we added it... it's used only for an agent (on Operator side) to understand where the agent is communicating to, as an agent may be using an IP address, a proxy, an FQDN, etc.

2021-07-12 23:06 UTC, lzimm commented on tools/translators/ftp/agent.py
> +        self.target = None
cool, yeah, i patched the actual schism one, but if that's all its used for then greatly simplifies things.

2021-07-13 12:56 UTC, privateducky approved these changes

2021-07-13 12:57 UTC, merged