ATT&CK Navigator connector plugin
preludeorg/operator-support pull request #33
Opened 2020-12-09 21:03 UTC by bfuzzy1

A simple plugin that adds ATT&CK Navigator to the Operator platform. Internet access is required for this plugin to work properly.

2020-12-09 21:13 UTC, privateducky requested changes
This is great - I love how lightweight this is. Can you rename the plugin "Navigator" so the file path will be: plugins/navigator/Navigator.html

I could see the space/copyright symbol being problematic on some folks machines.

By the way, one of our guys may add a full-screen option for plugins, which will allow this to get maximum space!

2020-12-09 21:31 UTC, bfuzzy1 commented
> This is great - I love how lightweight this is. Can you rename the plugin "Navigator" so the file path will be: plugins/navigator/Navigator.html
> 
> I could see the space/copyright symbol being problematic on some folks machines.
> 
> By the way, one of our guys may add a full-screen option for plugins, which will allow this to get maximum space!

Good call out on that symbol! Everything should be good to go now. Having full-screen would be awesome!

2020-12-09 22:43 UTC, privateducky commented on plugins/navigator/Navigator.html
> +    <object type="text/html" data="https://mitre-attack.github.io/attack-navigator/"  width="1200px" height="800px"style="overflow:auto;background:white">
@lzimm any quick tips to make this resizable with the window?

2020-12-09 22:43 UTC, privateducky commented on plugins/navigator/Navigator.html
> +<div>
one minor thing: looks like an orphan div here, you can delete that

2020-12-09 22:46 UTC, privateducky commented
I've been toying w/this for a few min. Easy interaction. I could see a future version allowing you to load navigator layers of your adversaries no problem. We'll get this merged in pretty soon, just want to see if we can auto-size the div to the window by chance.

2020-12-09 23:44 UTC, bfuzzy1 commented on plugins/navigator/Navigator.html
> +<div>
Removed that in this [commit](https://github.com/preludeorg/operator-support/pull/33/commits/26b56b2ee8f159681b59d2058cf416f94b9a3a9f)

2020-12-09 23:45 UTC, bfuzzy1 commented on plugins/navigator/Navigator.html
> +    <object type="text/html" data="https://mitre-attack.github.io/attack-navigator/"  width="1200px" height="800px"style="overflow:auto;background:white">
Fixed that in this [commit](https://github.com/preludeorg/operator-support/pull/33/commits/26b56b2ee8f159681b59d2058cf416f94b9a3a9f)

2020-12-09 23:49 UTC, bfuzzy1 commented
@privateducky Everything should be fixed now!

2020-12-10 14:33 UTC, privateducky approved these changes
great work!

2020-12-10 14:33 UTC, merged